#!/usr/bin/env python3
"""PreCompact hook: snapshots the transcript and writes a handover before compaction.

Runs on matcher auto|manual. Copies the full transcript JSONL into .claude/backups/,
prunes to the last 10, and writes state/handover-latest.md, which the SessionStart hook
re-injects after compaction. Fails silent (exit 0) on any error.
"""
import json
import shutil
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
STATE = ROOT / "state"
BACKUPS = ROOT / ".claude" / "backups"
KEEP = 10


def read(path, limit=8000):
    try:
        return path.read_text(encoding="utf-8")[:limit].strip()
    except Exception:
        return ""


def recent_messages(transcript_path, n=12):
    """Return the last n (role, text) human/assistant messages from the transcript JSONL."""
    msgs = []
    try:
        lines = Path(transcript_path).read_text(encoding="utf-8").splitlines()
    except Exception:
        return msgs
    for line in lines:
        try:
            entry = json.loads(line)
        except Exception:
            continue
        role = entry.get("type") or entry.get("role") or "?"
        message = entry.get("message", {})
        content = message.get("content") if isinstance(message, dict) else None
        text = ""
        if isinstance(content, str):
            text = content
        elif isinstance(content, list):
            for block in content:
                if isinstance(block, dict) and block.get("type") == "text":
                    text += block.get("text", "")
        if text.strip():
            msgs.append((role, text.strip()))
    return msgs[-n:]


def main():
    try:
        raw = sys.stdin.read()
        data = json.loads(raw) if raw.strip() else {}
    except Exception:
        data = {}

    trigger = data.get("trigger", "auto")
    transcript_path = data.get("transcript_path", "")
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")

    BACKUPS.mkdir(parents=True, exist_ok=True)
    backup_name = f"transcript_{trigger}_{stamp}.jsonl"
    backup_ok = False
    if transcript_path:
        try:
            shutil.copy2(transcript_path, BACKUPS / backup_name)
            backup_ok = True
        except Exception:
            backup_ok = False

    # Keep only the most recent KEEP transcript snapshots.
    try:
        snaps = sorted(BACKUPS.glob("transcript_*.jsonl"), key=lambda p: p.stat().st_mtime)
        for old in snaps[:-KEEP]:
            old.unlink(missing_ok=True)
    except Exception:
        pass

    msgs = recent_messages(transcript_path) if transcript_path else []
    convo = "\n\n".join(f"**{r}:** {t[:600]}" for r, t in msgs) or "(transcript unavailable)"
    backup_line = f"`.claude/backups/{backup_name}`" if backup_ok else "(transcript copy failed)"

    handover = f"""# Handover — latest

> AUTO-GENERATED by the PreCompact hook on {stamp} (trigger: {trigger}).
> The SessionStart hook re-injects this after a compact / clear.

## Backup
Full transcript saved to: {backup_line}

## state/active_context.md (snapshot)
{read(STATE / 'active_context.md') or '(empty)'}

## state/progress.md (snapshot)
{read(STATE / 'progress.md') or '(empty)'}

## Last messages before compaction
{convo}

## Next step
Resume from `state/active_context.md`. Re-read `CLAUDE.md` and `.claude/SYCOPHANCY.md`.
"""
    try:
        (STATE / "handover-latest.md").write_text(handover, encoding="utf-8")
    except Exception:
        pass
    sys.exit(0)


if __name__ == "__main__":
    try:
        main()
    except Exception:
        sys.exit(0)
