#!/usr/bin/env python3
"""build-adapters.py

Generates OpenAI Codex / Agent-Skills adapters from the canonical Claude Code
layout (.claude/skills/, .claude/agents/, .mcp.json[.example]) so a single
"brain" works across several harnesses.

Outputs (all regenerated from the .claude/ sources on every run):
  - .agents/skills/<name>/          full recursive copy of each .claude/skills/<name>/
                                     directory, with SKILL.md frontmatter trimmed to the
                                     Agent Skills spec fields.
  - .agents/skills/README.md        note that these are generated copies.
  - .codex/agents/<name>.toml       one TOML file per .claude/agents/<name>.md subagent.
  - .codex/config.toml              MCP server config translated from .mcp.json[.example].
  - .github/workflows/adapters-check.yml
                                     CI that runs this script with --check.

Usage:
    python tools/build-adapters.py            write the outputs, print a summary
    python tools/build-adapters.py --check    compare generated output to what is on
                                               disk (byte-for-byte); print every
                                               differing path; exit 1 on any difference,
                                               0 if everything is up to date. Writes
                                               nothing to the repo.

Python 3.9+, standard library only.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

CLAUDE_SKILLS_DIR = REPO_ROOT / ".claude" / "skills"
CLAUDE_AGENTS_DIR = REPO_ROOT / ".claude" / "agents"
MCP_EXAMPLE_PATH = REPO_ROOT / ".mcp.json.example"
MCP_PLAIN_PATH = REPO_ROOT / ".mcp.json"

GENERATED_COMMENT = (
    "# GENERATED by tools/build-adapters.py — do not edit; "
    "edit the .claude/ source and re-run."
)

CODEX_CONFIG_NOTE = (
    "# Fill env values or export them in your shell; Codex does not expand ${VAR}. "
    "Project-level MCP config only applies to trusted projects."
)

AGENTS_SKILLS_README = """# Generated skill adapters

These are generated copies of `.claude/skills/` for harnesses that read `.agents/skills/`
(Codex, Gemini CLI, Cursor). Regenerated with `python tools/build-adapters.py`.

Do not edit these files by hand — edit the source under `.claude/skills/` and re-run the
build script.
"""

ADAPTERS_CHECK_WORKFLOW = """name: adapters-check

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: python tools/build-adapters.py --check
"""

# Agent Skills spec frontmatter fields to keep in generated SKILL.md copies.
SKILL_FRONTMATTER_KEEP_KEYS = (
    "name",
    "description",
    "license",
    "compatibility",
    "metadata",
    "allowed-tools",
)

# A top-level YAML frontmatter key: starts at column 0, e.g. "name:" or "allowed-tools:".
TOP_LEVEL_KEY_RE = re.compile(r"^([A-Za-z0-9_.-]+):(?:\s|$)")

BARE_TOML_KEY_RE = re.compile(r"^[A-Za-z0-9_-]+$")

PLACEHOLDER_ENV_RE = re.compile(r"^\$\{[A-Za-z_][A-Za-z0-9_]*\}$")


class MalformedInputError(Exception):
    """Raised for a source file that cannot be parsed; the caller logs and skips it."""


@dataclass
class BuildResult:
    skill_count: int = 0
    agent_count: int = 0
    mcp_count: int = 0
    dropped_skill_keys: set = field(default_factory=set)
    dropped_agent_keys: set = field(default_factory=set)
    warnings: list = field(default_factory=list)


# --------------------------------------------------------------------------
# Small IO helpers — UTF-8, LF-only, no implicit newline translation.
# --------------------------------------------------------------------------

def read_text_normalized(path: Path) -> str:
    """Read a UTF-8 text file, normalising any CRLF/CR to LF."""
    data = path.read_bytes()
    text = data.decode("utf-8")
    return text.replace("\r\n", "\n").replace("\r", "\n")


def write_text_lf(path: Path, text: str) -> None:
    """Write text as UTF-8 with LF line endings, regardless of platform."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write(text)


def copy_normalized(src: Path, dst: Path) -> None:
    """Copy src to dst. Text (UTF-8 decodable) files are newline-normalised to LF;
    anything else is copied byte-for-byte."""
    data = src.read_bytes()
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError:
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(src, dst)
        return
    normalized = text.replace("\r\n", "\n").replace("\r", "\n")
    write_text_lf(dst, normalized)


# --------------------------------------------------------------------------
# Shared frontmatter parsing (used by both skills and agents).
# --------------------------------------------------------------------------

def split_frontmatter(text: str, src_label: str) -> tuple[list[str], list[str]]:
    """Split raw markdown text into (frontmatter_lines, body_lines).

    frontmatter_lines excludes the opening/closing '---' delimiter lines.
    body_lines is everything after the closing delimiter, verbatim (so a leading
    blank line, if present in the source, is preserved).
    """
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        raise MalformedInputError(f"{src_label}: missing opening '---' frontmatter delimiter")
    end_idx = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            end_idx = i
            break
    if end_idx is None:
        raise MalformedInputError(f"{src_label}: missing closing '---' frontmatter delimiter")
    return lines[1:end_idx], lines[end_idx + 1:]


def group_frontmatter(frontmatter_lines: list[str]) -> list[tuple[str, list[str]]]:
    """Group raw frontmatter lines into (key, raw_lines_incl_key_line) blocks, in
    source order. Continuation lines (indented, or part of a multi-line YAML value)
    stay attached to the preceding key. Any lines before the first top-level key are
    dropped (not expected in well-formed frontmatter)."""
    blocks: list[tuple[str, list[str]]] = []
    current_key = None
    current_lines: list[str] = []
    for line in frontmatter_lines:
        m = TOP_LEVEL_KEY_RE.match(line)
        if m:
            if current_key is not None:
                blocks.append((current_key, current_lines))
            current_key = m.group(1)
            current_lines = [line]
        else:
            if current_key is not None:
                current_lines.append(line)
            # else: stray preamble line before any key — dropped
    if current_key is not None:
        blocks.append((current_key, current_lines))
    return blocks


def extract_scalar_value(raw_lines: list[str]) -> str:
    """Best-effort extraction of a single string value from a frontmatter key block.
    Handles plain scalars (the common case here) and makes a reasonable attempt at
    quoted scalars and block scalars (| and >), without being a full YAML parser."""
    first_line = raw_lines[0]
    _, _, rest = first_line.partition(":")
    rest = rest.strip()
    continuation = [l.strip() for l in raw_lines[1:] if l.strip()]

    if rest in ("|", "|-", "|+"):
        return "\n".join(raw_lines[1:])
    if rest in (">", ">-", ">+"):
        return " ".join(continuation)
    if rest:
        value = rest
        if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
            inner = value[1:-1]
            if value[0] == '"':
                inner = inner.replace('\\"', '"').replace("\\\\", "\\")
            value = inner
        if continuation:
            value = value + " " + " ".join(continuation)
        return value
    return " ".join(continuation)


# --------------------------------------------------------------------------
# 1. Skills -> .agents/skills/
# --------------------------------------------------------------------------

def gather_skill_dirs() -> list[Path]:
    if not CLAUDE_SKILLS_DIR.exists():
        return []
    return sorted(p for p in CLAUDE_SKILLS_DIR.iterdir() if p.is_dir())


def write_transformed_skill_md(src: Path, dst: Path) -> list[str]:
    """Copy a SKILL.md, keeping only the Agent Skills spec frontmatter keys. Returns
    the list of dropped keys."""
    text = read_text_normalized(src)
    frontmatter_lines, body_lines = split_frontmatter(text, str(src))
    blocks = group_frontmatter(frontmatter_lines)

    kept_lines: list[str] = []
    dropped: list[str] = []
    for key, raw in blocks:
        if key in SKILL_FRONTMATTER_KEEP_KEYS:
            kept_lines.extend(raw)
        else:
            dropped.append(key)

    new_lines = ["---"] + kept_lines + ["---"] + body_lines
    write_text_lf(dst, "\n".join(new_lines))
    return dropped


def build_skill(skill_dir: Path, target_dir: Path) -> list[str]:
    skill_md = skill_dir / "SKILL.md"
    if not skill_md.is_file():
        raise MalformedInputError(f"{skill_dir}: no SKILL.md found — skill skipped")

    target_dir.mkdir(parents=True, exist_ok=True)
    dropped: list[str] = []
    for src in sorted(skill_dir.rglob("*")):
        rel = src.relative_to(skill_dir)
        dst = target_dir / rel
        if src.is_dir():
            dst.mkdir(parents=True, exist_ok=True)
            continue
        dst.parent.mkdir(parents=True, exist_ok=True)
        if src == skill_md:
            dropped.extend(write_transformed_skill_md(src, dst))
        else:
            copy_normalized(src, dst)
    return dropped


# --------------------------------------------------------------------------
# 2. Subagents -> .codex/agents/*.toml
# --------------------------------------------------------------------------

def gather_agent_files() -> list[Path]:
    if not CLAUDE_AGENTS_DIR.exists():
        return []
    return sorted(p for p in CLAUDE_AGENTS_DIR.iterdir() if p.is_file() and p.suffix == ".md")


def toml_basic_string_inline(s: str) -> str:
    """A single-line TOML basic string. Collapses embedded newlines to spaces."""
    s = s.replace("\r\n", " ").replace("\n", " ").replace("\r", " ")
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20 or ord(ch) == 0x7F:
            out.append("\\u%04x" % ord(ch))
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def toml_escape_basic_multiline(s: str) -> str:
    """Escape content for a TOML multi-line basic string (\"\"\"...\"\"\"). Literal
    newlines and tabs are left as-is (both are permitted raw inside \"\"\"...\"\"\")."""
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch in ("\n", "\t"):
            out.append(ch)
        elif ord(ch) < 0x20 or ord(ch) == 0x7F:
            out.append("\\u%04x" % ord(ch))
        else:
            out.append(ch)
    return "".join(out)


def build_agent_toml(md_path: Path) -> tuple[str, list[str]]:
    text = read_text_normalized(md_path)
    frontmatter_lines, body_lines = split_frontmatter(text, str(md_path))
    blocks = group_frontmatter(frontmatter_lines)

    values: dict = {}
    dropped: list[str] = []
    for key, raw in blocks:
        if key in ("name", "description"):
            values[key] = extract_scalar_value(raw)
        else:
            dropped.append(key)

    if "name" not in values or "description" not in values:
        raise MalformedInputError(
            f"{md_path}: missing required 'name' or 'description' frontmatter key"
        )

    body = "\n".join(body_lines)
    body_block = body if body.endswith("\n") else body + "\n"

    header = (
        GENERATED_COMMENT + "\n\n"
        f"name = {toml_basic_string_inline(values['name'])}\n"
        f"description = {toml_basic_string_inline(values['description'])}\n"
    )

    if "'''" in body:
        escaped = toml_escape_basic_multiline(body_block)
        instructions = f'developer_instructions = """\n{escaped}"""\n'
    else:
        instructions = f"developer_instructions = '''\n{body_block}'''\n"

    return header + instructions, dropped


# --------------------------------------------------------------------------
# 3. MCP -> .codex/config.toml
# --------------------------------------------------------------------------

def load_mcp_config() -> dict:
    if MCP_EXAMPLE_PATH.exists():
        path = MCP_EXAMPLE_PATH
    elif MCP_PLAIN_PATH.exists():
        path = MCP_PLAIN_PATH
    else:
        return {}
    text = read_text_normalized(path)
    try:
        data = json.loads(text)
    except json.JSONDecodeError as e:
        raise MalformedInputError(f"{path}: invalid JSON ({e})")
    if not isinstance(data, dict):
        raise MalformedInputError(f"{path}: top-level JSON value is not an object")
    return data


def toml_table_key(name: str) -> str:
    if BARE_TOML_KEY_RE.match(name):
        return name
    return toml_basic_string_inline(name)


def build_codex_config(data: dict) -> tuple[str, int]:
    servers = data.get("mcpServers") or {}
    lines = [GENERATED_COMMENT, CODEX_CONFIG_NOTE, ""]
    count = 0
    for name, cfg in servers.items():
        if not isinstance(cfg, dict):
            continue
        count += 1
        lines.append(f"[mcp_servers.{toml_table_key(name)}]")
        if "command" in cfg:
            lines.append(f"command = {toml_basic_string_inline(str(cfg['command']))}")
        args = cfg.get("args")
        if args is not None:
            args_str = ", ".join(toml_basic_string_inline(str(a)) for a in args)
            lines.append(f"args = [{args_str}]")
        env = cfg.get("env")
        if env:
            parts = []
            for k, v in env.items():
                if isinstance(v, str) and PLACEHOLDER_ENV_RE.match(v):
                    parts.append(f'{toml_table_key(k)} = ""')
                else:
                    parts.append(f"{toml_table_key(k)} = {toml_basic_string_inline(str(v))}")
            lines.append("env = { " + ", ".join(parts) + " }")
        lines.append("")
    text = "\n".join(lines).rstrip("\n") + "\n"
    return text, count


# --------------------------------------------------------------------------
# Generation entry point — always builds into a scratch root, mirroring the
# real repo-relative layout, so the same tree can be diffed (--check) or
# synced onto the repo (default).
# --------------------------------------------------------------------------

def generate_all(scratch_root: Path) -> BuildResult:
    result = BuildResult()

    agents_skills_root = scratch_root / ".agents" / "skills"
    agents_skills_root.mkdir(parents=True, exist_ok=True)
    for skill_dir in gather_skill_dirs():
        target_dir = agents_skills_root / skill_dir.name
        try:
            dropped = build_skill(skill_dir, target_dir)
        except MalformedInputError as e:
            result.warnings.append(str(e))
            continue
        result.dropped_skill_keys.update(dropped)
        result.skill_count += 1
    write_text_lf(agents_skills_root / "README.md", AGENTS_SKILLS_README)

    codex_agents_root = scratch_root / ".codex" / "agents"
    codex_agents_root.mkdir(parents=True, exist_ok=True)
    for md_path in gather_agent_files():
        try:
            toml_text, dropped = build_agent_toml(md_path)
        except MalformedInputError as e:
            result.warnings.append(str(e))
            continue
        write_text_lf(codex_agents_root / f"{md_path.stem}.toml", toml_text)
        result.dropped_agent_keys.update(dropped)
        result.agent_count += 1

    try:
        mcp_data = load_mcp_config()
    except MalformedInputError as e:
        result.warnings.append(str(e))
        mcp_data = {}
    config_text, mcp_count = build_codex_config(mcp_data)
    result.mcp_count = mcp_count
    write_text_lf(scratch_root / ".codex" / "config.toml", config_text)

    write_text_lf(
        scratch_root / ".github" / "workflows" / "adapters-check.yml",
        ADAPTERS_CHECK_WORKFLOW,
    )

    return result


# --------------------------------------------------------------------------
# Diff (--check) and sync (write) against the real repo.
# --------------------------------------------------------------------------

def list_files(root: Path) -> dict:
    if not root.exists():
        return {}
    return {p.relative_to(root).as_posix(): p for p in root.rglob("*") if p.is_file()}


_CRLF = bytes((13, 10))
_LF = bytes((10,))


def _norm(path: Path) -> bytes:
    # Fold CRLF to LF before comparing: a Windows checkout with core.autocrlf=true
    # rewrites mirrored files with CRLF while git stores them LF. Not drift.
    return path.read_bytes().replace(_CRLF, _LF)


def diff_dir(scratch_dir: Path, repo_dir: Path, label: str) -> list[str]:
    scratch_files = list_files(scratch_dir)
    repo_files = list_files(repo_dir)
    diffs = []
    for rel in sorted(set(scratch_files) - set(repo_files)):
        diffs.append(f"missing: {label}/{rel}")
    for rel in sorted(set(repo_files) - set(scratch_files)):
        diffs.append(f"stale:   {label}/{rel}")
    for rel in sorted(set(scratch_files) & set(repo_files)):
        if _norm(scratch_files[rel]) != _norm(repo_files[rel]):
            diffs.append(f"changed: {label}/{rel}")
    return diffs


def diff_file(scratch_file: Path, repo_file: Path, label: str) -> list[str]:
    if not repo_file.exists():
        return [f"missing: {label}"]
    if _norm(scratch_file) != _norm(repo_file):
        return [f"changed: {label}"]
    return []


def sync_dir(scratch_dir: Path, repo_dir: Path) -> None:
    scratch_files = list_files(scratch_dir)
    repo_files = list_files(repo_dir) if repo_dir.exists() else {}
    for rel, p in repo_files.items():
        if rel not in scratch_files:
            p.unlink()
    if repo_dir.exists():
        for d in sorted(
            (p for p in repo_dir.rglob("*") if p.is_dir()),
            key=lambda p: len(p.parts),
            reverse=True,
        ):
            if not any(d.iterdir()):
                d.rmdir()
    for rel, src in scratch_files.items():
        dst = repo_dir / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(src, dst)


def sync_file(scratch_file: Path, repo_file: Path) -> None:
    repo_file.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(scratch_file, repo_file)


def targets(scratch_root: Path) -> list[tuple]:
    return [
        ("dir", scratch_root / ".agents" / "skills", REPO_ROOT / ".agents" / "skills", ".agents/skills"),
        ("dir", scratch_root / ".codex" / "agents", REPO_ROOT / ".codex" / "agents", ".codex/agents"),
        ("file", scratch_root / ".codex" / "config.toml", REPO_ROOT / ".codex" / "config.toml", ".codex/config.toml"),
        (
            "file",
            scratch_root / ".github" / "workflows" / "adapters-check.yml",
            REPO_ROOT / ".github" / "workflows" / "adapters-check.yml",
            ".github/workflows/adapters-check.yml",
        ),
    ]


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate Codex / Agent-Skills adapters from the .claude/ sources."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Compare generated output to disk; print differing paths; exit 1 on drift.",
    )
    args = parser.parse_args()

    with tempfile.TemporaryDirectory(prefix="build-adapters-") as tmp:
        scratch_root = Path(tmp)
        result = generate_all(scratch_root)

        if args.check:
            all_diffs: list[str] = []
            for kind, scratch_path, repo_path, label in targets(scratch_root):
                if kind == "dir":
                    all_diffs.extend(diff_dir(scratch_path, repo_path, label))
                else:
                    all_diffs.extend(diff_file(scratch_path, repo_path, label))
            for d in sorted(all_diffs):
                print(d)
            return 1 if all_diffs else 0

        for kind, scratch_path, repo_path, _label in targets(scratch_root):
            if kind == "dir":
                sync_dir(scratch_path, repo_path)
            else:
                sync_file(scratch_path, repo_path)

        for w in result.warnings:
            print(f"warning: {w}", file=sys.stderr)
        print(f"{result.skill_count} skills, {result.agent_count} agents, {result.mcp_count} MCP servers")
        return 0


if __name__ == "__main__":
    sys.exit(main())
